package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.PathVariable;
// imports for use List, Map, String and Object
import java.util.List;
import java.util.Map;
import java.lang.String;
import java.lang.Object;

import org.springframework.jdbc.core.JdbcTemplate;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {

	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
  	private JdbcTemplate jdbcTemplate;

	@PostMapping(path="/listar") // Map ONLY POST Requests
	public @ResponseBody String addNewAlumno (@RequestParam String curso
			, @RequestParam String apellido) {
		Alumno n = new Alumno();
		n.setName(curso);
		n.setName(apellido);
		alumnoRepository.save(n);
		return "Saved";		
	}

	@PostMapping(path="/nuevo curso")

	public @ResponseBody String addNewAlumno(@RequestParam String curso
			 ) {
		Alumno n = new Alumno();
		n.setName(curso);		
		userRepository.save(n);
		return "Saved";		
	}

	@PostMapping(path="/eliminarcurso")
	
	public @ResponseBody String addNewUser (@RequestParam String curso
			, @RequestParam String apellido) {
		Alumno n = new Alumno();
		n.setName(curso);
		n.setEmail(2);
		alumnoRepository.save(n);
		return "Saved";		}
	

	@DeleteMapping(path="/del")
	public @ResponseBody String delAlumno (@RequestParam Integer id) {
		Alumno n = new Alumno();
		n.setId(id);
		AlumnoRepository.delete(n);
		return "Deleted";
	}

	@PutMapping(path="/edit")
	public @ResponseBody String editAlumno (@RequestParam Integer id, @RequestParam String name
	, @RequestParam String email) {
		Alumno = new Alumno();
		n.setId(id);
		n.setName(name);		
		alumnoRepository.save(n);
		return "Updated";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Alumno> getAllAlumno() {
		return AlumnoRepository.findAll();
	}

	@GetMapping(path="/get/{id}")
	public @ResponseBody Alumno getOneUser(@PathVariable Integer id) {
		return alumnoRepository.findById(id).orElse(null);
	}


	@GetMapping(path="/get/report")
	public @ResponseBody List<Map<String, Object>> getReport() {
		List<Map<String, Object>> queryResult = jdbcTemplate.queryForList("SELECT CONCAT(name, ' ==> ', email) as mycol FROM user");
		return queryResult;
	}


}
